version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: eu-central-1
    CLUSTER_NAME: eksDeepDiveFrankfurt
    NAMESPACE: ns-davi-lab3
    APP_NAME: todo-davi-lab3
phases:
  install:
    commands:
      - curl -sLo kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.34.1/2025-09-19/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - yum -y install jq
  pre_build:
    commands:
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
      - echo "Lendo imagem gerada no estágio build"
      - IMAGE=$(jq -r '.image' image.json)
      - TAG=$(jq -r '.tag' image.json)
      - FULL_IMAGE="$IMAGE:$TAG"
  build:
    commands:
      - echo "Aplicando namespace e recursos base"
      - kubectl apply -f k8s/namespace.yaml
      - kubectl get deploy $APP_NAME-deploy -n $NAMESPACE || kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
      - kubectl apply -f k8s/service.yaml -n $NAMESPACE
      - echo "Atualizando imagem do deployment"
      - kubectl set image deployment/$APP_NAME-deploy $APP_NAME=$FULL_IMAGE -n $NAMESPACE --record
  post_build:
    commands:
      - kubectl rollout status deployment/$APP_NAME-deploy -n $NAMESPACE --timeout=180s
artifacts:
  files:
    - image.json
