version: 0.2

phases:
  install:
    commands:
      - echo ">> Instalando dependências (jq + kubectl)"
      # instala jq no Ubuntu/Debian (standard:7.0). Se for AL2/AL2023, cai no yum/dnf.
      - |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update && apt-get install -y jq
        elif command -v yum >/dev/null 2>&1; then
          yum -y install jq
        elif command -v dnf >/dev/null 2>&1; then
          dnf -y install jq
        else
          echo "Nenhum gerenciador de pacotes suportado encontrado"; exit 1
        fi
      - curl -sLo /usr/local/bin/kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.34.1/2025-09-19/bin/linux/amd64/kubectl
      - chmod +x /usr/local/bin/kubectl
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME

  pre_build:
    commands:
      - echo ">> Contexto kubectl"
      - kubectl version --client=true
      - kubectl get ns || true
      - kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

  build:
    commands:
      - echo ">> Aplicando manifests"
      - kubectl apply -f k8s/namespace.yaml
      - kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
      - kubectl apply -f k8s/service.yaml -n $NAMESPACE
      - echo ">> Recursos"
      - kubectl get deploy,svc,pods -n $NAMESPACE

  post_build:
    commands:
      - echo "Deploy finalizado"
artifacts:
  files:
    - image.json
